// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuwjkdqaztuziilsxzhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1d2prZHFhenR1emlpbHN4emhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTM4NjUsImV4cCI6MjA1NDg2OTg2NX0.jx6ZziEJ1U3JGwZ5iqaore4SAFDTb4-aFPJTtjD7v7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);